# Generated by Django 4.2.3 on 2023-07-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='skills',
            field=models.TextField(),
        ),
    ]
